name: Build Android

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2    
        
      - name: Install Ionic and Cordova
        run: sudo npm install -g @ionic/cli cordova       
      
      - name: Build Android
        run: ionic cordova build android

      - name: Upload Android App
        uses: actions/upload-artifact@v2.2.0
        with:
          name: android          
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk   

      - name: Build iOS
        run: ionic cordova build ios 

      - name: Upload iOS App
        uses: actions/upload-artifact@v2.2.0
        with:
          name: ios          
          path: platforms/ios/build/emulator/MyApp.app
