name: Build Android

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2    
        
      - name: Install Ionic and Cordova
        run: sudo npm install -g @ionic/cli cordova
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build Android
        run: ionic cordova build android
    
